<?php

namespace Aizatto\Bundle\NBePayBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NBePayTransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NBePayTransactionRepository extends EntityRepository
{
}